<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, organizational-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<div>
    <from action="/signUp" method = "post">
        <input name="fio" placeholder="ФИО">
        <input name="event" placeholder="Событие">
        <input name="category" placeholder="Категория">
        <input name="data" placeholder="Дата">
        <input type = "submit" value="Добавить">
    </from>
</div>
    <td> <a href="organizationals">Назад</a> </td>
</body>
</html>